import numpy as np
print(" WEEKLY DATA REPORT --- OLA ")
marks = np.array([60, 75, 80, 45, 90])
sales = np.array([120, 200, 150, 90, 300])
age   = np.array([18, 25, 40, 60, 70])
bp    = np.array([140, 120, 130, 150, 160])

print("=" * 40)
print("     STUDENT ANALYSIS")
print("=" * 40)
print("average mark: ", marks.mean())
print("higest Mark: ", marks.max())
print("lowest mark: ", marks.min())
print("passed: ", marks[marks >= 50])
print("failed: ", marks[marks < 50 ])

print("=" * 40)
print("     SALES ANALYSIS")
print("=" * 40)
print("Total: $", sales.sum())
print("higest sales: ", sales.max())
print("lowest sales: ", sales.min())
print("high days: ",sales[sales >= 200])
print("low days: ", sales[sales < 200])

print("=" * 40)
print("     HEALTH ANALYSIS")
print("=" * 40)
risk = (age > 50) & (bp > 140)
print("high risk count: ", np.sum(risk))
print("high risk age: ", age[risk])
print("safe age: ", age[~risk])
